Add validation for component.yaml v1.1 configuration file
choreo-templates/choreo-source-config-validator pull request #22
Opened 2024-11-08 08:46 UTC by chira99

## Purpose
The new `component.yaml v1.1` needs to be validated during `source configuration file validation` step in a component build. So we need to $subject

## Goal
- Proper validation of the updated `dependencies` section in `component.yaml v1.1` file.

## Approach
- Added validation logic for the new dependency type (`connectionReferences`).
- Updated Regex checks for each service type (service, thirdparty, database) to ensure strict validation in both v1.0 and v1.1 component.yaml files
- Added tests to cover the validation of v1.1 and updated tests of v1.0 to cover strict validation of each resourceRef field.

2024-11-12 05:25 UTC, binoyPeries requested changes

2024-11-12 05:25 UTC, binoyPeries commented on test/component-yaml-samples.js
> +    #0
```suggestion
 
```
Please remove these numbers

2024-11-12 08:35 UTC, yashodgayashan commented
@chira99 please note that you need to update the CICD component as well.

2024-11-21 05:32 UTC, chira99 commented on test/component-yaml-samples.js
> +    #0
Resolved with e429eddf8435941578956923d56fe5b1f8ada691

2024-11-21 05:37 UTC, chira99 commented
> @chira99 please note that you need to update the CICD component as well.

ACK

2024-11-21 06:01 UTC, binoyPeries approved these changes

2024-11-21 06:02 UTC, merged

2024-11-21 06:27 UTC, yashodgayashan commented
@chira99 do we have an issue to track this? If not please create one and complete it because we are doing Argo parallel and this can cause a BREAKING CHANGE.